---
abstract: "Gets contents of /sys/class in terms of 'classes' (directories of /sys/class), 'devices' (subdirectory of class) and 'attributes' (contents of directories."
author:
  - 'mimosinnet <mimosinet at cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acpi-Battery
version: 0.001
